# Generated by Django 4.2.30 on 2026-08-13 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان')),
                ('text', models.TextField(verbose_name='توضیحات')),
                ('icon_class', models.CharField(help_text='مثال: flaticon-light-bulb', max_length=100, verbose_name='کلاس آیکون')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'مرحله کاری',
                'verbose_name_plural': 'مراحل کاری',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SliderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('subtitle', models.TextField(blank=True, verbose_name='توضیح کوتاه')),
                ('image', models.ImageField(upload_to='core/slider/', verbose_name='تصویر')),
                ('button_text', models.CharField(default='آشنایی بیشتر', max_length=50, verbose_name='متن دکمه')),
                ('button_link', models.URLField(blank=True, verbose_name='لینک دکمه')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
            ],
            options={
                'verbose_name': 'اسلاید',
                'verbose_name_plural': 'اسلایدها',
                'ordering': ['order'],
            },
        ),
    ]
