# Generated by Django 4.2.30 on 2026-08-13 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slideritem',
            name='button_text',
            field=models.CharField(blank=True, default='آشنایی بیشتر', max_length=50, verbose_name='متن دکمه'),
        ),
    ]
