# Generated by Django 4.2.30 on 2026-07-23 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='icon_class',
            field=models.CharField(blank=True, help_text='نام کلاس آیکون (مثال: fa fa-home برای FontAwesome یا flaticon-helmet-1 برای FlatIcon)', max_length=100),
        ),
    ]
