# Generated by Django 4.2.30 on 2026-07-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_service_icon_class'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='category',
        ),
        migrations.AddField(
            model_name='service',
            name='category',
            field=models.ManyToManyField(related_name='services', to='services.servicecategory'),
        ),
    ]
