# Generated by Django 4.2.30 on 2026-07-24 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_category_service_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='advantages',
            field=models.TextField(blank=True, help_text='مزایای این سرویس را بنویسید'),
        ),
        migrations.AddField(
            model_name='service',
            name='our_approach',
            field=models.TextField(blank=True, help_text='توضیحات مربوط به رویکرد ما'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_design',
            field=models.TextField(blank=True, help_text='مرحله طراحی'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_execution',
            field=models.TextField(blank=True, help_text='مرحله خروجی نهایی'),
        ),
        migrations.AddField(
            model_name='service',
            name='process_research',
            field=models.TextField(blank=True, help_text='مرحله تحقیق'),
        ),
    ]
