# Generated by Django 4.2.30 on 2026-07-24 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_service_advantages_service_our_approach_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='process_design',
        ),
        migrations.RemoveField(
            model_name='service',
            name='process_execution',
        ),
        migrations.RemoveField(
            model_name='service',
            name='process_research',
        ),
        migrations.CreateModel(
            name='ServiceStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان تحقیق')),
                ('text', models.TextField(verbose_name='متن توضیحات')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/steps/', verbose_name='تصویر مرحله(اختیاری')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتییب نمایش')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='services.service', verbose_name='سرویس مربوطه')),
            ],
            options={
                'verbose_name': 'مرحله سرویس',
                'verbose_name_plural': 'مراحل سرویس',
                'ordering': ['order'],
            },
        ),
    ]
