# Generated by Django 4.2.30 on 2026-07-24 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_remove_service_process_design_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='work_proccess',
            field=models.TextField(blank=True, help_text='پروسه کاری'),
        ),
    ]
