# Generated by Django 4.2.30 on 2026-07-24 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_service_work_proccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='extra_image1',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
        migrations.AddField(
            model_name='service',
            name='extra_image2',
            field=models.ImageField(blank=True, null=True, upload_to='services/'),
        ),
    ]
