# Generated by Django 4.2.30 on 2026-08-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_service_extra_image1_service_extra_image2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['name'], 'verbose_name': 'خدمات '},
        ),
        migrations.AlterField(
            model_name='service',
            name='advantages',
            field=models.TextField(blank=True, help_text='مزایای این سرویس را بنویسید 2'),
        ),
    ]
