# Generated by Django 4.2.30 on 2026-08-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_shoptag_shopproduct_tags'),
        ('services', '0008_alter_service_options_alter_service_advantages'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='shop_products',
            field=models.ManyToManyField(blank=True, related_name='services', to='shop.shopproduct', verbose_name='محصولات مرتبط'),
        ),
    ]
