# Generated by Django 4.2.30 on 2026-08-13 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteBackground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_bg', models.ImageField(help_text='بک\u200cگراند بخش نظرات مشتریان', upload_to='backgrounds/')),
            ],
            options={
                'verbose_name': 'بک\u200cگراند سایت',
                'verbose_name_plural': 'بک\u200cگراندهای سایت',
            },
        ),
    ]
