# Generated by Django 4.2.30 on 2026-07-29 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopproductimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproduct',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='review_count',
            field=models.IntegerField(default=0),
        ),
    ]
