# Generated by Django 4.2.30 on 2026-08-15 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_shopproduct_rating_shopproduct_review_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shopcategory',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='shopproductimage',
            options={'verbose_name': 'تصویر محصول', 'verbose_name_plural': 'تصاویر محصول'},
        ),
        migrations.AlterField(
            model_name='shopcategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='category',
            field=models.ManyToManyField(related_name='shop_products', to='shop.shopcategory', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ثبت'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='rating',
            field=models.FloatField(default=0.0, verbose_name='امتیاز'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='review_count',
            field=models.IntegerField(default=0, verbose_name='تعداد نظرات'),
        ),
        migrations.AlterField(
            model_name='shopproduct',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='اسلاگ'),
        ),
        migrations.AlterField(
            model_name='shopproductimage',
            name='shop_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_image', to='shop.shopproduct', verbose_name='محصول'),
        ),
    ]
