# Generated by Django 4.2.30 on 2026-08-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_shopcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'تگ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.AddField(
            model_name='shopproduct',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='shop.shoptag', verbose_name='تگ ها'),
        ),
    ]
