# Generated by Django 4.2.30 on 2026-07-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='portfolio/instagram/', verbose_name='تصویر')),
            ],
            options={
                'verbose_name': 'تصویر اینستاگرام',
                'verbose_name_plural': 'تصویرهای اینستاگرام',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='PortFolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان دسته بندی')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='PortfolioTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام تگ')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'تگ ',
                'verbose_name_plural': 'تگ ها',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='عنوان')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='portfolio/images/', verbose_name='تصویر شاخص')),
                ('short_description', models.TextField(blank=True, max_length=500, verbose_name='خلاصه متن')),
                ('content', models.TextField(verbose_name='متن کامل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال بودن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ انتشار')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین ویرایش')),
                ('categories', models.ManyToManyField(related_name='post', to='portfolio.portfoliocategory', verbose_name='دسسته بندی های')),
                ('tags', models.ManyToManyField(blank=True, related_name='portfolio', to='portfolio.portfoliotag', verbose_name='تگ ها')),
            ],
            options={
                'verbose_name': 'نمونه کار/پست',
                'verbose_name_plural': 'نمونه کارها/پست ها',
                'ordering': ['-created_at'],
            },
        ),
    ]
