# Generated by Django 4.2.30 on 2026-07-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='categories',
            field=models.ManyToManyField(related_name='post', related_query_name='portfolio_set', to='portfolio.portfoliocategory', verbose_name='دسسته بندی های'),
        ),
    ]
