# Generated by Django 4.2.30 on 2026-07-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_portfolio_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='categories',
            field=models.ManyToManyField(related_name='post', to='portfolio.portfoliocategory', verbose_name='دسسته بندی های'),
        ),
    ]
