# Generated by Django 4.2.30 on 2026-07-24 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_remove_service_category_service_category'),
        ('products', '0002_product_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='service',
        ),
        migrations.AddField(
            model_name='product',
            name='service',
            field=models.ManyToManyField(blank=True, related_name='products', to='services.service', verbose_name='سرویس مرتبط'),
        ),
    ]
